---
- name: "Content Switching Scenario"
  hosts: "localhost"
  gather_facts: no
  connection: "local"
  vars_files:
    - "../common_vars/avi_credentials.yml"
  
  tasks:
          
    - name: Create list of required template files
      set_fact:
        avi_config_templates:
          - "../templates/healthmonitor_avi_config.j2"
          - "../templates/persistence_profile_avi_config.j2"
          - "../templates/pool_avi_config.j2"
          - "../templates/vsvip_avi_config.j2"
          - "../templates/http_policy_avi_config.j2"
          - "../templates/virtualservice_avi_config.j2"

    - name: Shared VIP Scenario | Setup ALL
      import_role:
        name: "../roles/create_vs"
      vars:
        combined_avi_config: "{{ avi_config }}"

