---
- name: "Shared VIP Scenario"
  hosts: "localhost"
  gather_facts: no
  connection: "local"
  vars_files:
    - "../common_vars/avi_credentials.yml"
  
  tasks:
    - block:
        - name: Retrieve Avi vsVIP
          vmware.alb.avi_api_session:
            avi_credentials: "{{ avi_credentials }}"
            api_context: "{{ avi_api_context | default(omit) }}"
            http_method: get
            path: "vsvip/?name={{ vs_parameters.shared_vsvip_name }}"
            tenant: "{{ tenant_name }}"
          register: fetched_vsvip
          
        - name: Set vsvip_ref from fetched vsvip
          set_fact:
            vsvip_ref: "/api/vsvip/{{ fetched_vsvip.obj.results[0].uuid }}" 
          when: fetched_vsvip.obj.results | length > 0 
        # - name: Print vsvip_ref
        #   debug: 
        #     var: vsvip_ref
      when: vs_parameters.shared_vsvip_name is defined 

    - name: Create list of required template files
      set_fact:
        avi_config_templates:
          - "../templates/healthmonitor_avi_config.j2"
          - "../templates/persistence_profile_avi_config.j2"
          - "../templates/pool_avi_config.j2"
          - "../templates/vsvip_avi_config.j2"
          - "../templates/http_policy_avi_config.j2"
          - "../templates/virtualservice_avi_config.j2"

    - name: Shared VIP Scenario | Setup ALL
      import_role:
        name: "../roles/create_vs"
      vars:
        combined_avi_config: "{{ avi_config }}"

