---
- name: "Shared Pool Scenario"
  hosts: "localhost"
  gather_facts: no
  connection: "local"
  vars_files:
    - "../common_vars/avi_credentials.yml"
  
  tasks:
    - block:
      - name: Retrieve Avi pool
        vmware.alb.avi_api_session:
          avi_credentials: "{{ avi_credentials }}"
          api_context: "{{ avi_api_context | default(omit) }}"
          http_method: get
          path: "pool/?name={{ pool_parameters.pools.shared_pool_name }}"
          tenant: "{{ tenant_name }}"
        register: fetched_pool
        
      - name: Set pool_ref from fetched pool
        set_fact:
          pool_ref: "/api/pool/?name={{ fetched_pool.obj.results[0].name }}" 
        when: fetched_pool is defined
      when: pool_parameters.pools.shared_pool_name is defined
          
    - name: Create list of required template files
      set_fact:
        avi_config_templates:
          - "../templates/healthmonitor_avi_config.j2"
          - "../templates/persistence_profile_avi_config.j2"
          - "../templates/pool_avi_config.j2"
          - "../templates/vsvip_avi_config.j2"
          - "../templates/virtualservice_avi_config.j2"

    - name: Shared VIP Scenario | Setup ALL
      import_role:
        name: "../roles/create_vs"
      vars:
        combined_avi_config: "{{ avi_config }}"

